version: '3.8'

services:

  app:
    container_name: my_cont2
    depends_on:
      - mongodb
    ports:
      - "8081:8080"
    build:
      context: .
      dockerfile: Dockerfile

  mongodb:
    image: mongo:6
    container_name: my_mongodb_cont
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
