server.port=8080

spring.output.ansi.enabled=ALWAYS
spring.jpa.database-platform=org.hibernate.dialect.PostgresPlusDialect
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always

spring.datasource.url=jdbc:postgresql://postgres:5432/quadraticEquationDB
spring.datasource.username=postgres
spring.datasource.password=password

spring.mvc.view.suffix=.html